rvm:
    - "1.8.7"
    - "1.9.3-p551"
    - "2.0.0-p598"
    - "2.1.5"
    - "2.2.0"
    - "jruby-1.7.18"
env:
    - FORTITUDE_SPECS_RAILS_VERSION=4.2.0
    - FORTITUDE_SPECS_RAILS_VERSION=4.1.9
    - FORTITUDE_SPECS_RAILS_VERSION=4.0.13
    - FORTITUDE_SPECS_RAILS_VERSION=3.2.21
    - FORTITUDE_SPECS_RAILS_VERSION=3.1.12
    - FORTITUDE_SPECS_RAILS_VERSION=3.0.20
    - FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=4.2.0
    - FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=3.0.20
before_script:
    - export JRUBY_OPTS="$JRUBY_OPTS -J-Xmx128m -J-Xms128m -J-Xss2048k"
matrix:
    exclude:
        # Rails 4.x doesn't support Ruby 1.8.7
        -   rvm: 1.8.7
            env: FORTITUDE_SPECS_RAILS_VERSION=4.2.0
        -   rvm: 1.8.7
            env: FORTITUDE_SPECS_RAILS_VERSION=4.1.9
        -   rvm: 1.8.7
            env: FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=4.2.0
        -   rvm: 1.8.7
            env: FORTITUDE_SPECS_RAILS_VERSION=4.0.13
        # 2014-06-19 ageweke -- ARGH. After trying about seventeen different things, no matter what I do,
        # Travis fails JRuby builds about 20% of the time with "Killed". Their documentation indicates that this
        # is likely an out-of-memory issue (i.e., entire VM's memory is consumed). However, I'm running JRuby with
        # only 128MB allocated to each VM (per above) -- yuck -- and it's still happening; this makes no sense, as it
        # would take something like 20+ concurrent JRuby processes to consume 3GB, and we should never be running
        # more than 2-3.
        #
        # At this point, I have little choice other than to mark these as 'allowed failures', and check in on each
        # one manually to make sure there aren't other failures, too. This is very frustrating, but I can't seem to
        # find a way around it. If there's a fix out there somewhere, I'm all ears!
    allow_failures:
        -   rvm: jruby-1.7.18
            env: FORTITUDE_SPECS_RAILS_VERSION=4.2.0
        -   rvm: jruby-1.7.18
            env: FORTITUDE_SPECS_RAILS_VERSION=4.1.9
        -   rvm: jruby-1.7.18
            env: FORTITUDE_SPECS_RAILS_VERSION=4.0.13
        -   rvm: jruby-1.7.18
            env: FORTITUDE_SPECS_RAILS_VERSION=3.2.21
        -   rvm: jruby-1.7.18
            env: FORTITUDE_SPECS_RAILS_VERSION=3.1.12
        -   rvm: jruby-1.7.18
            env: FORTITUDE_SPECS_RAILS_VERSION=3.0.20
        -   rvm: jruby-1.7.18
            env: FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=4.2.0
        -   rvm: jruby-1.7.18
            env: FORTITUDE_NATIVE_EXTENSIONS=false FORTITUDE_SPECS_RAILS_VERSION=3.0.20
